Porting //eve/staging/2019-HAMINGJA->//eve/development/MAINLINE at head (1567531) - using branchspec //eve/staging/2019-HAMINGJA->//eve/development/MAINLINE
========================================

Change 1565008 by bara@eve_branches_staging_2019-HAMINGJA_bara-pc on 2019/09/10 13:20:17

cluError: clientDogmaLocation.py(1436) GatherDroneInfo - AttributeError
https://jira.ccpgames.com/browse/TQ-132607

 - it doesn't seemt to find the drone (droneItem is None), so in those cases we just continue with the loop rather than error on it

========================================

Change 1565085 by eric@eric_MAINLINE_FOR_REAL on 2019/09/10 14:29:14

Submit Wwise project changes with Jita XL audio edits.
https://jira.ccpgames.com/browse/GFX-5878

========================================

Change 1565109 by louxun@louxun-contrib on 2019/09/10 14:39:48

Some dogma getter has been changed to generators, so use list() to expand those


DEFECT: https://jira.ccpgames.com/browse/TTC-2040

========================================

Change 1565206 by hrafng@eve_branches_staging_2019-HAMINGJA_hrafn-pc on 2019/09/10 15:17:16

Lowsec Invasions are not being distributed/scheduled https://jira.ccpgames.com/browse/TQ-132611 We don't want the lowsec invasions to count towards the maximum of "3 invasion tales active at one time" that we used for the staged roll-out. It needs to use it's own maxDistributions parameter to decide how many of those tales should be running.

========================================

Change 1565254 by kristjans@kristjans-ws-main on 2019/09/10 15:39:02

ESP-1661 - Be able to click Email and Mac Address to see users

CORE 1092

Review: http://codecollaborator/ui#review:id=17358

========================================

Change 1565335 by bara@eve_branches_staging_2019-HAMINGJA_bara-pc on 2019/09/10 16:27:41

Fitting Warning shown for Drone Damage Amplifier when ship has fighters in its launch tube but not in its fighter bay
https://jira.ccpgames.com/browse/TQ-132615

 - this was happening because fighters that are in the tubes are not saved in a fit, and I was working off the fit
 - changed it so we specifically get the fighter types in the tubes

TO TEST: make sure this works for both simulation and actual ship

========================================

Change 1565634 by markw@eve_branches_staging_2019-HAMINGJA_mark-ws on 2019/09/11 10:07:13

Character customization A/B test;  Randomized clothing, large randomize button.
https://jira.ccpgames.com/browse/TMS-107

========================================

Change 1565812 by eric@eric_MAINLINE_FOR_REAL on 2019/09/11 12:35:07

[eve 2019-HAMINGJA][audio] Fix for defect where the language of audio voice overs does not change from English when another language is selected.
https://jira.ccpgames.com/browse/TQ-132608

========================================

Change 1565850 by eric@eric_MAINLINE_FOR_REAL on 2019/09/11 13:01:33

[eve 2019-HAMINGJA][audio] Fix build errors in audio2
https://jira.ccpgames.com/browse/TQ-132608

========================================

Change 1565899 by thordurm@thordurm_thordurm-ws_6031 on 2019/09/11 13:30:35

Potential future bug in picking up "/language=foo" code

========================================

Change 1565973 by eric@eric_MAINLINE_FOR_REAL on 2019/09/11 13:52:51

[eve 2019-HAMINGJA][audio] * wwise audio edits to Jita giving it multiple stages of audio ambience over its construction period.
* sound bank generation for these edits

https://jira.ccpgames.com/browse/GFX-5878

========================================

Change 1566077 by javier@EVE_DEVELOPMENT_JAVIER-WS on 2019/09/11 14:47:34

Republishing Sleeper and Violent Wormholes for VFx fix https://jira.ccpgames.com/browse/TQ-132625

========================================

Change 1566083 by dmaxson@dmaxson_DMAXSON-WS_1633 on 2019/09/11 14:49:41

Pass stringified ban type ID to BannedEvent publisher

========================================

Change 1566094 by thordurm@thordurm_thordurm-ws_6031 on 2019/09/11 14:51:14

Language menu bug:
https://jira.ccpgames.com/browse/TQ-132613

========================================

Change 1566109 by javier@EVE_DEVELOPMENT_JAVIER-WS on 2019/09/11 15:00:42

Republishing the controller for the new CS9 Jita station ambience  https://jira.ccpgames.com/browse/GFX-5878

========================================

Change 1566155 by bara@eve_branches_staging_2019-HAMINGJA_bara-pc on 2019/09/11 15:31:45

Fitting: Shield Boost Amplifier does not count Abyssal Shield Boosters for warning messages
https://jira.ccpgames.com/browse/TQ-132623

 - changing it so we find all the abyssal modules on the ship, and when we are collecting the attributes needed, we use that dictionary to look up the attributes for the type
 - each new validation function needs to take this into account and deal with it if it's using attributes to figure stuff out
 - I added checks for mixedTurret sized, even though we don't have mutaplasmid turrets yet

========================================

Change 1566220 by bara@eve_branches_staging_2019-HAMINGJA_bara-pc on 2019/09/11 16:12:24

cluError: TypeError: OnClick() got an unexpected keyword argument 'openGroup'
https://jira.ccpgames.com/browse/TQ-132631

 - changing it so OnClick in MarketMetaGroupEntry accepts keywords, and that seems to not only get rid of the exception but restore the intended functionality

========================================

Change 1566248 by bara@eve_branches_staging_2019-HAMINGJA_bara-pc on 2019/09/11 16:31:07

cluError: AttributeError: 'NoneType' object has no attribute 'sr'
https://jira.ccpgames.com/browse/TQ-132632

 - changing it so instead of sending the panel from the node to the function, we just send the typeID from the node since that's all we need anyways

========================================

Change 1566460 by marshall@marshall_MARSHALL-WS_4433 on 2019/09/12 07:39:46

Last batch of HAMINGJA zh translation & enable ship SKINs on Serenity.

========================================

Change 1566635 by baldur@eve_mainline_BALDUR-WS on 2019/09/12 11:42:43

Audio level adjustments for wormholes

https://jira.ccpgames.com/browse/TQ-132620

========================================

Change 1566772 by kristjang@kristjang_KRISTJANG-WS_HAMINGJA-ref on 2019/09/12 14:05:42

Merging using //eve/development/MAINLINE->//eve/staging/2019-HAMINGJA

https://jira.ccpgames.com/browse/TQ-132541

========================================

Change 1566801 by bara@eve_branches_staging_2019-HAMINGJA_bara-pc on 2019/09/12 14:17:49

Multiple skills cannot be bought at once with "skills on demand" if the client is in Russian
https://jira.ccpgames.com/browse/TQ-132635

 - formatting of the string to display in the conformation box did not work in Russian so I fixed it

========================================

Change 1567036 by hrafng@eve_branches_staging_2019-HAMINGJA_hrafn-pc on 2019/09/13 09:22:36

Too Many Invasion Tales Scheduled https://jira.ccpgames.com/browse/TQ-132642 Invasion template schedules too many future tales when running tails get stopped or if the scheduler runs when less than three tales are currently active and replacements for the missing tale have already been scheduled. Fixing the order in which tales get replaced, prioritizing those that end last, and leaving replacement of missing tales to the very end. This should mean that left to its own devices the system should properly stabilize at three tales given time and you should never have more than that until you schedule them yourself. It also means that if you kill a tale the system will not try to jump in and refill that tale for you right away, which is fine.

========================================

Change 1567248 by kristjans@kristjans-ws-main on 2019/09/13 14:23:00

Consistent Information across ESP User Lists
https://jira.ccpgames.com/browse/ESP-1660

Review: http://codecollaborator/ui#review:id=17359

========================================

Change 1567385 by ingthor@ingthor_MAIN on 2019/09/13 16:10:45

Improve post process tweener to not hold strong references to scenes. Also improve post process tweener to not be time dialated
https://jira.ccpgames.com/browse/TQ-132626

========================================

Change 1567484 by bara@eve_branches_staging_2019-HAMINGJA_bara-pc on 2019/09/13 17:19:06

Fitting Warnings: Warnings are enabled when window first opens
https://jira.ccpgames.com/browse/TQ-132644

 - fixing it so all the warning icons start off being hidden and the labels are not initialized with the number 4 as text :D

========================================

Change 1567496 by eric@eric_MAINLINE_FOR_REAL on 2019/09/13 17:24:37

[eve 2019-HAMINGJA][audio] Wormhole sound edits to fix defect where wormhole shrinking sound does not pierce through enough: https://jira.ccpgames.com/browse/TQ-132620

========================================

Change 1567531 by bara@eve_branches_staging_2019-HAMINGJA_bara-pc on 2019/09/13 19:42:14

Fitting Warnings: Fitting window shows fails to show skill icon when you are missing skills for a fit
https://jira.ccpgames.com/browse/TQ-132643

 - this was happening because when you open simulate fit directly, it will first load your current ship and then the simulated one. When loading the current ship, it needs to go to the server to get the hold data. While that was happening, the simulated ship was loaded, and the correct icon displayed. Then when the client finally got the hold data, it just continued with what it was doing and updated the icon, but it was no longer relevant.
 - changed it so if the dogmalocation is not the same as it was when we started getting the skills for the ship, we just stop that update of the icon as it's no longer relevant and the icon has or will be updated with the correct data

[git-p4: depot-paths = "//eve/branches/development/MAINLINE/carbon/src/audio2/": change = 1567919]